//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.HumanResource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HumanResourceEntities : DbContext
    {
        public HumanResourceEntities()
            : base("name=HumanResourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MaBoPhan> MaBoPhans { get; set; }
        public virtual DbSet<MaPhongBan> MaPhongBans { get; set; }
        public virtual DbSet<tblDanhSachNhanVien> tblDanhSachNhanViens { get; set; }
        public virtual DbSet<tblHoSoLyLichNhanVien> tblHoSoLyLichNhanViens { get; set; }
        public virtual DbSet<MaQuocGia> MaQuocGias { get; set; }
        public virtual DbSet<MaTonGiao> MaTonGiaos { get; set; }
        public virtual DbSet<MaDanToc> MaDanTocs { get; set; }
    
        public virtual ObjectResult<sp_EmployeeGet_Result> sp_EmployeeGet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EmployeeGet_Result>("sp_EmployeeGet");
        }
    
        public virtual ObjectResult<sp_Employee_Get_Result> sp_Employee_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Employee_Get_Result>("sp_Employee_Get");
        }
    
        public virtual int sp_ActionLog(string actionName, string controllerName, string method, string content, string detail, string userName, Nullable<System.DateTime> date)
        {
            var actionNameParameter = actionName != null ?
                new ObjectParameter("ActionName", actionName) :
                new ObjectParameter("ActionName", typeof(string));
    
            var controllerNameParameter = controllerName != null ?
                new ObjectParameter("ControllerName", controllerName) :
                new ObjectParameter("ControllerName", typeof(string));
    
            var methodParameter = method != null ?
                new ObjectParameter("Method", method) :
                new ObjectParameter("Method", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            var detailParameter = detail != null ?
                new ObjectParameter("Detail", detail) :
                new ObjectParameter("Detail", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActionLog", actionNameParameter, controllerNameParameter, methodParameter, contentParameter, detailParameter, userNameParameter, dateParameter);
        }
    }
}
