//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.HumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaBoPhan
    {
        public string MaBoPhan1 { get; set; }
        public string TenBoPhan { get; set; }
        public string TenBoPhanA { get; set; }
        public string MaPhongBan { get; set; }
        public bool Nghi7 { get; set; }
        public Nullable<int> SoTT { get; set; }
        public string Nhom { get; set; }
        public Nullable<int> Order { get; set; }
    }
}
