//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.HumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDanhSachNhanVien
    {
        public string MaSoNhanVien { get; set; }
        public byte[] HinhAnh { get; set; }
        public string HoNhanVienA { get; set; }
        public string HoNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public string TenNhanVienA { get; set; }
        public string TenThuongGoi { get; set; }
        public string BiDanh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public bool GioiTinh { get; set; }
        public string NoiSinh { get; set; }
        public string NoiSinhA { get; set; }
        public string NguyenQuan { get; set; }
        public string TruQuan { get; set; }
        public string TruQuanA { get; set; }
        public string DiaChi { get; set; }
        public string DiaChiA { get; set; }
        public string SoCMND { get; set; }
        public string NoiCapCMND { get; set; }
        public string NoiCapCMNDA { get; set; }
        public Nullable<System.DateTime> NgayCapCMND { get; set; }
        public string QuocTich { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string ThanhPhanGiaDinh { get; set; }
        public string ThanhPhanBanThan { get; set; }
        public bool HonNhan { get; set; }
        public string SucKhoe { get; set; }
        public string SucKhoeA { get; set; }
        public Nullable<int> ChieuCao { get; set; }
        public string DienThoaiCQ { get; set; }
        public string DienThoaiNR { get; set; }
        public Nullable<int> DaGhi { get; set; }
        public bool BoDoi { get; set; }
        public string SophieuNP { get; set; }
        public string NamXN { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
