//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.HumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoSoLyLichNhanVien
    {
        public string MaSoNhanVien { get; set; }
        public string MaSoHoSo { get; set; }
        public string ChiNhanh { get; set; }
        public string TrinhDoVanHoa { get; set; }
        public string TrinhDoChuyenMon { get; set; }
        public string ChuyenNganh { get; set; }
        public string ChuyenNganhA { get; set; }
        public string TruongDaoTao { get; set; }
        public string HinhThucDaoTao { get; set; }
        public Nullable<short> NamTotNghiep { get; set; }
        public string XepLoaiTotNghiep { get; set; }
        public string NgoaiNguChinh { get; set; }
        public string TrinhDoNgoaiNgu { get; set; }
        public string TrinhDoTinHoc { get; set; }
        public Nullable<System.DateTime> NgayVaoCongDoan { get; set; }
        public string ChucVuCongDoan { get; set; }
        public string SoBaoHiemXaHoi { get; set; }
        public string SoBaoHiemYTe { get; set; }
        public string NoiDangKyKCB { get; set; }
        public string NoiDangKyKCBA { get; set; }
        public string BangCap { get; set; }
        public Nullable<double> LuongHD { get; set; }
        public Nullable<double> LuongTV { get; set; }
        public Nullable<float> Luonggoctr { get; set; }
        public Nullable<float> Luonggoc { get; set; }
        public Nullable<float> MucLuongtr { get; set; }
        public Nullable<double> MucLuong { get; set; }
        public Nullable<System.DateTime> NgayLenLuong { get; set; }
        public Nullable<double> PhuCap { get; set; }
        public Nullable<double> PhuCapKN { get; set; }
        public Nullable<int> PCChuyencan { get; set; }
        public Nullable<int> PCNha { get; set; }
        public Nullable<int> PCMultiSkill1 { get; set; }
        public Nullable<int> PCMultiSkill2 { get; set; }
        public Nullable<int> PCThamnien { get; set; }
        public Nullable<int> PCOEE { get; set; }
        public Nullable<int> PCTeamLeader { get; set; }
        public Nullable<int> PC6S { get; set; }
        public Nullable<int> PCExpert { get; set; }
        public Nullable<int> SpecialAllowance { get; set; }
        public Nullable<System.DateTime> PCChildren1 { get; set; }
        public Nullable<System.DateTime> PCChildren2 { get; set; }
        public Nullable<int> QCAllowance { get; set; }
        public Nullable<int> PCMeal { get; set; }
        public Nullable<int> PCTel { get; set; }
        public bool NetGross { get; set; }
        public string Loaingoaite { get; set; }
        public Nullable<System.DateTime> NgayHetHanHD { get; set; }
        public string ChucVuChinhQuyen { get; set; }
        public string Chucdanh { get; set; }
        public string HinhThucTuyenDung { get; set; }
        public Nullable<System.DateTime> NgayTinhThamNien { get; set; }
        public Nullable<System.DateTime> NgayVaoCQ { get; set; }
        public Nullable<System.DateTime> NgayThuViec { get; set; }
        public Nullable<System.DateTime> NgayKyHopDong { get; set; }
        public Nullable<System.DateTime> NgayHopDongRN { get; set; }
        public string SoHopDong { get; set; }
        public string SoHopDongRN { get; set; }
        public string BoPhan { get; set; }
        public string To { get; set; }
        public string LyDoChuyenCongTac { get; set; }
        public string SoSoLaoDong { get; set; }
        public Nullable<System.DateTime> NgayBHYT { get; set; }
        public Nullable<System.DateTime> NgayHetHanBHYT { get; set; }
        public string GhiChu { get; set; }
        public bool Workday { get; set; }
        public bool Thaisan { get; set; }
        public bool HC { get; set; }
        public string SoLocker { get; set; }
        public string SoPhieuDC { get; set; }
        public bool Office { get; set; }
        public string SophieuNV { get; set; }
        public string Mathoiviec { get; set; }
        public Nullable<System.DateTime> NgayBH { get; set; }
        public Nullable<int> KhauTruPhuThuoc { get; set; }
        public string DieuKien { get; set; }
        public string DocHai { get; set; }
    }
}
