//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.BarcodeScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingBarcodeQR_VNL
    {
        public long ID { get; set; }
        public string OCNo { get; set; }
        public string BarcodeID { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.DateTime> ScannedDateScan { get; set; }
        public Nullable<byte> StatusScan { get; set; }
        public Nullable<byte> StatusWH { get; set; }
        public string UserNameScan { get; set; }
        public string MachineNumberScan { get; set; }
        public Nullable<int> BusinessStatusID { get; set; }
        public Nullable<int> WHFromID { get; set; }
        public Nullable<int> WHToID { get; set; }
        public string WHFromKey { get; set; }
        public string WHToKey { get; set; }
        public string UserAdd { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string UserUpd { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
    }
}
