//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Label_GR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label_GR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Label_GR", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Module Role.
        /// </summary>
        internal static string AddModuleRole {
            get {
                return ResourceManager.GetString("AddModuleRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Part Code.
        /// </summary>
        internal static string AddPartCode {
            get {
                return ResourceManager.GetString("AddPartCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereich.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du sicher?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print QR Barcode Sales.
        /// </summary>
        internal static string BarcodeSales {
            get {
                return ResourceManager.GetString("BarcodeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print QR Barcode Sales - VNL.
        /// </summary>
        internal static string BarcodeSalesVNL {
            get {
                return ResourceManager.GetString("BarcodeSalesVNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korb.
        /// </summary>
        internal static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtstag der Woche.
        /// </summary>
        internal static string BirthdayInWeek {
            get {
                return ResourceManager.GetString("BirthdayInWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchung.
        /// </summary>
        internal static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taste.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalender.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann diese Mahlzeit nicht löschen.
        /// </summary>
        internal static string CanNotDeleteMeal {
            get {
                return ResourceManager.GetString("CanNotDeleteMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kannst du nur Samstag wählen.
        /// </summary>
        internal static string CanYouChooseOnlySaturday {
            get {
                return ResourceManager.GetString("CanYouChooseOnlySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veränderung.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache ändern.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändere das Passwort.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern Sie Ihre Kontoeinstellungen.
        /// </summary>
        internal static string ChangeYourAccountSettings {
            get {
                return ResourceManager.GetString("ChangeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaudern.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie eine Mahlzeit.
        /// </summary>
        internal static string ChooseMeal {
            get {
                return ResourceManager.GetString("ChooseMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie die Schicht.
        /// </summary>
        internal static string ChooseShift {
            get {
                return ResourceManager.GetString("ChooseShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands completed successfully.
        /// </summary>
        internal static string CommandsCompletedSuccessfully {
            get {
                return ResourceManager.GetString("CommandsCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komplett.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigen.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort bestätigen.
        /// </summary>
        internal static string ConfirmnNewPassword {
            get {
                return ResourceManager.GetString("ConfirmnNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhalt.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schalttafel.
        /// </summary>
        internal static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort erstellen.
        /// </summary>
        internal static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben keinen lokalen Benutzernamen / Passwort für diese Site. Fügen Sie ein lokales Konto hinzu, damit Sie sich ohne externen Login anmelden können..
        /// </summary>
        internal static string CreatePasswordDescription {
            get {
                return ResourceManager.GetString("CreatePasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateneingabe ist falsch.
        /// </summary>
        internal static string DataInputIsIncorrect {
            get {
                return ResourceManager.GetString("DataInputIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtsdatum.
        /// </summary>
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum und Uhrzeit müssen größer als der aktuelle Monat sein.
        /// </summary>
        internal static string DateTimeMustBeGreaterThanTheCurrentMonth {
            get {
                return ResourceManager.GetString("DateTimeMustBeGreaterThanTheCurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitstag.
        /// </summary>
        internal static string DateWork {
            get {
                return ResourceManager.GetString("DateWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferung von Instant-Nudeln.
        /// </summary>
        internal static string DeliveryInstantNoodles {
            get {
                return ResourceManager.GetString("DeliveryInstantNoodles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abteilung.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        internal static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abteilung zum Modul.
        /// </summary>
        internal static string DeptToModule {
            get {
                return ResourceManager.GetString("DeptToModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentation.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name.
        /// </summary>
        internal static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppelte Buchungszeit.
        /// </summary>
        internal static string DuplicateBookingTime {
            get {
                return ResourceManager.GetString("DuplicateBookingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten duplizieren.
        /// </summary>
        internal static string DuplicateData {
            get {
                return ResourceManager.GetString("DuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Part Code.
        /// </summary>
        internal static string DuplicatePartCode {
            get {
                return ResourceManager.GetString("DuplicatePartCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiter.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeren.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endzeit.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Ausführen von Daten.
        /// </summary>
        internal static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltungstag.
        /// </summary>
        internal static string EventDay {
            get {
                return ResourceManager.GetString("EventDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltungsliste.
        /// </summary>
        internal static string EventList {
            get {
                return ResourceManager.GetString("EventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Objekt existiert bereits.
        /// </summary>
        internal static string ExistsObject {
            get {
                return ResourceManager.GetString("ExistsObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktor.
        /// </summary>
        internal static string Factor {
            get {
                return ResourceManager.GetString("Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon konnte nicht überprüft werden.
        /// </summary>
        internal static string FailedToVerifyPhone {
            get {
                return ResourceManager.GetString("FailedToVerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiblich.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feld (*) ist nicht leer.
        /// </summary>
        internal static string FieldNotEmpty {
            get {
                return ResourceManager.GetString("FieldNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhänger.
        /// </summary>
        internal static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen.
        /// </summary>
        internal static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password.
        /// </summary>
        internal static string ForgotPasswordConfirmation_Detail {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donnerstag.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freunde.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frofile.
        /// </summary>
        internal static string Frofile {
            get {
                return ResourceManager.GetString("Frofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ab Datum.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktionsliste.
        /// </summary>
        internal static string FunctionList {
            get {
                return ResourceManager.GetString("FunctionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemeines.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutschland.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gehe zu.
        /// </summary>
        internal static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benotungszeit.
        /// </summary>
        internal static string GradingTime {
            get {
                return ResourceManager.GetString("GradingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe zu funktionieren.
        /// </summary>
        internal static string GroupToFunction {
            get {
                return ResourceManager.GetString("GroupToFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuhause.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildadresse.
        /// </summary>
        internal static string ImageAddress {
            get {
                return ResourceManager.GetString("ImageAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Code.
        /// </summary>
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Anmeldeversuch.
        /// </summary>
        internal static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste nach Abteilung.
        /// </summary>
        internal static string ListByDepartment {
            get {
                return ResourceManager.GetString("ListByDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste der bestellten Speisen.
        /// </summary>
        internal static string ListOfOrderedMeal {
            get {
                return ResourceManager.GetString("ListOfOrderedMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste der bestellten Nudeln.
        /// </summary>
        internal static string ListOfOrderedNoodles {
            get {
                return ResourceManager.GetString("ListOfOrderedNoodles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Part Code.
        /// </summary>
        internal static string ListPartCode {
            get {
                return ResourceManager.GetString("ListPartCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sperren.
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Männlich.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim ersten Mal markieren.
        /// </summary>
        internal static string MarkInFirstTime {
            get {
                return ResourceManager.GetString("MarkInFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum zweiten Mal markieren.
        /// </summary>
        internal static string MarkInSecondTime {
            get {
                return ResourceManager.GetString("MarkInSecondTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materialstatus.
        /// </summary>
        internal static string MaterialStatus {
            get {
                return ResourceManager.GetString("MaterialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materialart.
        /// </summary>
        internal static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahlzeit.
        /// </summary>
        internal static string Meal {
            get {
                return ResourceManager.GetString("Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahlzeit lieferung.
        /// </summary>
        internal static string MealDelivery {
            get {
                return ResourceManager.GetString("MealDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahlzeit Lieferung Ausnahme.
        /// </summary>
        internal static string MealDeliveryException {
            get {
                return ResourceManager.GetString("MealDeliveryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahlzeitinfo oder Schichtinfo falsch.
        /// </summary>
        internal static string MealInfoOrShiftInfoIncorrect {
            get {
                return ResourceManager.GetString("MealInfoOrShiftInfoIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essenszeitplan.
        /// </summary>
        internal static string MealSchedule {
            get {
                return ResourceManager.GetString("MealSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In der Zwischenzeit können Sie zur Startseite zurückkehren oder das Suchformular verwenden.
        /// </summary>
        internal static string MeanwhileYouMayReturnToHomeOrTryUsingTheSearchForm {
            get {
                return ResourceManager.GetString("MeanwhileYouMayReturnToHomeOrTryUsingTheSearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitglieder.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menüpunkt.
        /// </summary>
        internal static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobiltelefon.
        /// </summary>
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal.
        /// </summary>
        internal static string Modal {
            get {
                return ResourceManager.GetString("Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul zum Gruppieren.
        /// </summary>
        internal static string ModuleToGroup {
            get {
                return ResourceManager.GetString("ModuleToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freitag.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monat.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staatsangehörigkeit.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Kennwort.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachrichten.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am Anfang stand eine kleine Leistenmanufaktur in der Schuhhauptstadt Pirmasens, die Liebe zum Sport und die Leidenschaft, Bestehendes zu perfektionieren.
        ///                                        &lt;br /&gt;
        ///                                        Heute ist framas Ihr global präsenter, verlässlicher Partner bei der Entwicklung und Herstellung von Hochleistungskomponenten für den Sport-, Funktions- und Modeschuh von morgen.
        ///                                        &lt;br /&gt;
        ///                                        Und w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewsContent {
            get {
                return ResourceManager.GetString("NewsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Performance für Spielfeld und Straße.
        /// </summary>
        internal static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachrichtentyp.
        /// </summary>
        internal static string NewsType {
            get {
                return ResourceManager.GetString("NewsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Objekt existiert nicht.
        /// </summary>
        internal static string NotExistsObject {
            get {
                return ResourceManager.GetString("NotExistsObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nichts.
        /// </summary>
        internal static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num.
        /// </summary>
        internal static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline bestellen.
        /// </summary>
        internal static string OfflineOrderMeal {
            get {
                return ResourceManager.GetString("OfflineOrderMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altes Passwort.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoppla! Etwas ist schief gelaufen.
        /// </summary>
        internal static string OopsSomethingWentWrong {
            get {
                return ResourceManager.GetString("OopsSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellte Mahlzeit.
        /// </summary>
        internal static string OrderedMeal {
            get {
                return ResourceManager.GetString("OrderedMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essen erfolgreich bestellen.
        /// </summary>
        internal static string OrderMealsSuccessfully {
            get {
                return ResourceManager.GetString("OrderMealsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Laufe der Zeit.
        /// </summary>
        internal static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Code.
        /// </summary>
        internal static string PartCode {
            get {
                return ResourceManager.GetString("PartCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Name.
        /// </summary>
        internal static string PartName {
            get {
                return ResourceManager.GetString("PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Name English.
        /// </summary>
        internal static string PartNameEn {
            get {
                return ResourceManager.GetString("PartNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtsort.
        /// </summary>
        internal static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte.
        /// </summary>
        internal static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose.
        /// </summary>
        internal static string PleaseChoose {
            get {
                return ResourceManager.GetString("PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie einen Artikel.
        /// </summary>
        internal static string PleaseChooseItem {
            get {
                return ResourceManager.GetString("PleaseChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie eine Mahlzeit.
        /// </summary>
        internal static string PleaseChooseMeal {
            get {
                return ResourceManager.GetString("PleaseChooseMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie eine Mahlzeit für die Geschäftszeiten.
        /// </summary>
        internal static string PleaseChooseMealForOfficeHours {
            get {
                return ResourceManager.GetString("PleaseChooseMealForOfficeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose user.
        /// </summary>
        internal static string PleaseChooseUser {
            get {
                return ResourceManager.GetString("PleaseChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Tag Monat Jahr ein.
        /// </summary>
        internal static string PleaseEnterDayMonthYear {
            get {
                return ResourceManager.GetString("PleaseEnterDayMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the role code.
        /// </summary>
        internal static string PleaseEnterRoleCode {
            get {
                return ResourceManager.GetString("PleaseEnterRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the role name.
        /// </summary>
        internal static string PleaseEnterRoleName {
            get {
                return ResourceManager.GetString("PleaseEnterRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enterthe department code.
        /// </summary>
        internal static string PleaseEnterTheDepartmentCode {
            get {
                return ResourceManager.GetString("PleaseEnterTheDepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the part code.
        /// </summary>
        internal static string PleaseEnterThePartCode {
            get {
                return ResourceManager.GetString("PleaseEnterThePartCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the part name.
        /// </summary>
        internal static string PleaseEnterThePartName {
            get {
                return ResourceManager.GetString("PleaseEnterThePartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the part name with English.
        /// </summary>
        internal static string PleaseEnterThePartNameEn {
            get {
                return ResourceManager.GetString("PleaseEnterThePartNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Daten ein.
        /// </summary>
        internal static string PleaseInputData {
            get {
                return ResourceManager.GetString("PleaseInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte setzen Sie Ihr Passwort zurück, indem Sie auf klicken.
        /// </summary>
        internal static string PleaseResetYourPasswordByClicking {
            get {
                return ResourceManager.GetString("PleaseResetYourPasswordByClicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie eine Abteilung aus.
        /// </summary>
        internal static string PleaseSelectADepartment {
            get {
                return ResourceManager.GetString("PleaseSelectADepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte versuchen Sie es erneut.
        /// </summary>
        internal static string PleaseTryAgain {
            get {
                return ResourceManager.GetString("PleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte aktualisieren Sie Ihre E-Mail.
        /// </summary>
        internal static string PleaseUpdateYourEmail {
            get {
                return ResourceManager.GetString("PleaseUpdateYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutz-Bestimmungen.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnelle E-Mail.
        /// </summary>
        internal static string QuickEmail {
            get {
                return ResourceManager.GetString("QuickEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren Sie sich als neuer Benutzer.
        /// </summary>
        internal static string RegisterAsANewUser {
            get {
                return ResourceManager.GetString("RegisterAsANewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erinnere dich an mich.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort zurücksetzen.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwortbestätigung zurücksetzen.
        /// </summary>
        internal static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort zurücksetzen.
        /// </summary>
        internal static string ResetPasswordDefault {
            get {
                return ResourceManager.GetString("ResetPasswordDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollen.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles name.
        /// </summary>
        internal static string RolesName {
            get {
                return ResourceManager.GetString("RolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Umsatz.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umsatzdiagramm.
        /// </summary>
        internal static string SalesGraph {
            get {
                return ResourceManager.GetString("SalesGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dienstag.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday Off.
        /// </summary>
        internal static string SaturdayOff {
            get {
                return ResourceManager.GetString("SaturdayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of staff who is registered Saturday Off is over 50%.
        /// </summary>
        internal static string SaturdayOffPOver {
            get {
                return ResourceManager.GetString("SaturdayOffPOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samstag der Planung.
        /// </summary>
        internal static string SaturdayOfPlanning {
            get {
                return ResourceManager.GetString("SaturdayOfPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sparen.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahmen.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschiebung.
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurzer Inhalt.
        /// </summary>
        internal static string ShortContent {
            get {
                return ResourceManager.GetString("ShortContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurznachrichten.
        /// </summary>
        internal static string ShortNews {
            get {
                return ResourceManager.GetString("ShortNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schieberegler.
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startzeit.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Startzeit darf nicht größer oder gleich der Endzeit sein.
        /// </summary>
        internal static string StartDateCanNotGreaterThanOrEqualEndDate {
            get {
                return ResourceManager.GetString("StartDateCanNotGreaterThanOrEqualEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startzeit kann nicht unter der aktuellen Zeit liegen.
        /// </summary>
        internal static string StartDateCanNotLessThanCurrentDate {
            get {
                return ResourceManager.GetString("StartDateCanNotLessThanCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Startzeit muss größer als der aktuelle Tag sein.
        /// </summary>
        internal static string StartTimeMustBeGreaterThanTheCurrentDay {
            get {
                return ResourceManager.GetString("StartTimeMustBeGreaterThanTheCurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegenstand.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mittwoch.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstützung.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonntag.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitleiste.
        /// </summary>
        internal static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miteinander ausgehen.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabenliste.
        /// </summary>
        internal static string ToDoList {
            get {
                return ResourceManager.GetString("ToDoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total working hour in month.
        /// </summary>
        internal static string TotalWorkingHourInMonth {
            get {
                return ResourceManager.GetString("TotalWorkingHourInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montag.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochladen.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzer.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzeroberfläche.
        /// </summary>
        internal static string UserInterface {
            get {
                return ResourceManager.GetString("UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzername.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzeranfrage.
        /// </summary>
        internal static string UserRequest {
            get {
                return ResourceManager.GetString("UserRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer zu Abteilung.
        /// </summary>
        internal static string UserToDept {
            get {
                return ResourceManager.GetString("UserToDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string VietNam {
            get {
                return ResourceManager.GetString("VietNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle ansehen.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISIO ermöglicht die Verwendung im internen Netzwerk oder die Verwendung von VPN, wenn Sie es von außen verwenden..
        /// </summary>
        internal static string VISIOUseFromOutside {
            get {
                return ResourceManager.GetString("VISIOUseFromOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besucher.
        /// </summary>
        internal static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Daten ein.
        /// </summary>
        internal static string WarningNullData {
            get {
                return ResourceManager.GetString("WarningNullData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samstag.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir werden sofort daran arbeiten, das zu beheben.
        /// </summary>
        internal static string WeWillWorkOnFixingThatRightAway {
            get {
                return ResourceManager.GetString("WeWillWorkOnFixingThatRightAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu den Bürozeiten arbeiten.
        /// </summary>
        internal static string WorkingByOfficeHours {
            get {
                return ResourceManager.GetString("WorkingByOfficeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schichtarbeit.
        /// </summary>
        internal static string WorkingByShift {
            get {
                return ResourceManager.GetString("WorkingByShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hour on MES topic.
        /// </summary>
        internal static string WorkingHourOnMESTopic {
            get {
                return ResourceManager.GetString("WorkingHourOnMESTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahr.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie dürfen nur tagsüber buchen.
        /// </summary>
        internal static string YouAreOnlyAllowedToBookingDuringTheDay {
            get {
                return ResourceManager.GetString("YouAreOnlyAllowedToBookingDuringTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Passwort wurde zurück gesetzt.
        /// </summary>
        internal static string YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenReset", resourceCulture);
            }
        }
    }
}
