//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.OEEMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OEEMSEntities : DbContext
    {
        public OEEMSEntities()
            : base("name=OEEMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblComp> tblComps { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblDepartmentProcess> tblDepartmentProcesses { get; set; }
        public virtual DbSet<tblDownTime> tblDownTimes { get; set; }
        public virtual DbSet<tblGroupDT> tblGroupDTs { get; set; }
        public virtual DbSet<tblOEEMS_DownTime> tblOEEMS_DownTime { get; set; }
        public virtual DbSet<tblOEEMS_Employee> tblOEEMS_Employee { get; set; }
        public virtual DbSet<tblOEEMS_Header> tblOEEMS_Header { get; set; }
        public virtual DbSet<tblOEEMS_Process> tblOEEMS_Process { get; set; }
        public virtual DbSet<tblOEEMS_Status> tblOEEMS_Status { get; set; }
        public virtual DbSet<tblProcess> tblProcesses { get; set; }
        public virtual DbSet<tblProject> tblProjects { get; set; }
        public virtual DbSet<tblProjectComp> tblProjectComps { get; set; }
        public virtual DbSet<tblProjectSize> tblProjectSizes { get; set; }
        public virtual DbSet<tblSize> tblSizes { get; set; }
        public virtual DbSet<tblVersionTablet> tblVersionTablets { get; set; }
        public virtual DbSet<tblWorkpiece> tblWorkpieces { get; set; }
        public virtual DbSet<tblWorkpieceProcess> tblWorkpieceProcesses { get; set; }
        public virtual DbSet<tblLog> tblLogs { get; set; }
        public virtual DbSet<tblOEEMS_PercentComplete> tblOEEMS_PercentComplete { get; set; }
        public virtual DbSet<tblOEEMS_RealTime> tblOEEMS_RealTime { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
    
        public virtual ObjectResult<get_CboProjectExists_Result> get_CboProjectExists(string projectID)
        {
            var projectIDParameter = projectID != null ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_CboProjectExists_Result>("get_CboProjectExists", projectIDParameter);
        }
    
        public virtual ObjectResult<get_CboProjectExistsData_Result> get_CboProjectExistsData(string projectID)
        {
            var projectIDParameter = projectID != null ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_CboProjectExistsData_Result>("get_CboProjectExistsData", projectIDParameter);
        }
    
        public virtual ObjectResult<get_data_dropdown_Result> get_data_dropdown(string paraone, string paratwo, string parathree, string parafour)
        {
            var paraoneParameter = paraone != null ?
                new ObjectParameter("paraone", paraone) :
                new ObjectParameter("paraone", typeof(string));
    
            var paratwoParameter = paratwo != null ?
                new ObjectParameter("paratwo", paratwo) :
                new ObjectParameter("paratwo", typeof(string));
    
            var parathreeParameter = parathree != null ?
                new ObjectParameter("parathree", parathree) :
                new ObjectParameter("parathree", typeof(string));
    
            var parafourParameter = parafour != null ?
                new ObjectParameter("parafour", parafour) :
                new ObjectParameter("parafour", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_data_dropdown_Result>("get_data_dropdown", paraoneParameter, paratwoParameter, parathreeParameter, parafourParameter);
        }
    
        public virtual int get_OEEMS_DownTimeByID(string oEEID, string workPieceID, string processID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_OEEMS_DownTimeByID", oEEIDParameter, workPieceIDParameter, processIDParameter);
        }
    
        public virtual int get_OEEMS_EmployeeByID(string oEEID, string workPieceID, string processID, string eMPID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var eMPIDParameter = eMPID != null ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_OEEMS_EmployeeByID", oEEIDParameter, workPieceIDParameter, processIDParameter, eMPIDParameter);
        }
    
        public virtual ObjectResult<get_OEEMS_ProcessByID_Result> get_OEEMS_ProcessByID(string oEEID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMS_ProcessByID_Result>("get_OEEMS_ProcessByID", oEEIDParameter);
        }
    
        public virtual ObjectResult<get_OEEMS_ProcessSUMByID_Result> get_OEEMS_ProcessSUMByID(string oEEID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMS_ProcessSUMByID_Result>("get_OEEMS_ProcessSUMByID", oEEIDParameter);
        }
    
        public virtual ObjectResult<get_OEEMS_RealTime_Emp_Result> get_OEEMS_RealTime_Emp(string oEEID, string workPieceID, string processID, string eMPID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var eMPIDParameter = eMPID != null ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMS_RealTime_Emp_Result>("get_OEEMS_RealTime_Emp", oEEIDParameter, workPieceIDParameter, processIDParameter, eMPIDParameter);
        }
    
        public virtual int get_OEEMS_RealTimeByID(string oEEID, string workPieceID, string processID, string eMPID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var eMPIDParameter = eMPID != null ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_OEEMS_RealTimeByID", oEEIDParameter, workPieceIDParameter, processIDParameter, eMPIDParameter);
        }
    
        public virtual ObjectResult<get_OEEMS_ResultDistanceDate_Result> get_OEEMS_ResultDistanceDate(string oEEDateFrom, string oEEDateTo)
        {
            var oEEDateFromParameter = oEEDateFrom != null ?
                new ObjectParameter("OEEDateFrom", oEEDateFrom) :
                new ObjectParameter("OEEDateFrom", typeof(string));
    
            var oEEDateToParameter = oEEDateTo != null ?
                new ObjectParameter("OEEDateTo", oEEDateTo) :
                new ObjectParameter("OEEDateTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMS_ResultDistanceDate_Result>("get_OEEMS_ResultDistanceDate", oEEDateFromParameter, oEEDateToParameter);
        }
    
        public virtual ObjectResult<get_OEEMS_ResultDTDistanceDate_Result> get_OEEMS_ResultDTDistanceDate(string oEEDateFrom, string oEEDateTo)
        {
            var oEEDateFromParameter = oEEDateFrom != null ?
                new ObjectParameter("OEEDateFrom", oEEDateFrom) :
                new ObjectParameter("OEEDateFrom", typeof(string));
    
            var oEEDateToParameter = oEEDateTo != null ?
                new ObjectParameter("OEEDateTo", oEEDateTo) :
                new ObjectParameter("OEEDateTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMS_ResultDTDistanceDate_Result>("get_OEEMS_ResultDTDistanceDate", oEEDateFromParameter, oEEDateToParameter);
        }
    
        public virtual ObjectResult<get_OEEMS_ResultProcessDistanceDate_Result> get_OEEMS_ResultProcessDistanceDate(string oEEDateFrom, string oEEDateTo)
        {
            var oEEDateFromParameter = oEEDateFrom != null ?
                new ObjectParameter("OEEDateFrom", oEEDateFrom) :
                new ObjectParameter("OEEDateFrom", typeof(string));
    
            var oEEDateToParameter = oEEDateTo != null ?
                new ObjectParameter("OEEDateTo", oEEDateTo) :
                new ObjectParameter("OEEDateTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMS_ResultProcessDistanceDate_Result>("get_OEEMS_ResultProcessDistanceDate", oEEDateFromParameter, oEEDateToParameter);
        }
    
        public virtual ObjectResult<get_OEEMSHeaderByDate_Result> get_OEEMSHeaderByDate(string oEEDate)
        {
            var oEEDateParameter = oEEDate != null ?
                new ObjectParameter("OEEDate", oEEDate) :
                new ObjectParameter("OEEDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSHeaderByDate_Result>("get_OEEMSHeaderByDate", oEEDateParameter);
        }
    
        public virtual ObjectResult<get_OEEMSHeaderByDistanceDate_Result> get_OEEMSHeaderByDistanceDate(string oEEDateFrom, string oEEDateTo)
        {
            var oEEDateFromParameter = oEEDateFrom != null ?
                new ObjectParameter("OEEDateFrom", oEEDateFrom) :
                new ObjectParameter("OEEDateFrom", typeof(string));
    
            var oEEDateToParameter = oEEDateTo != null ?
                new ObjectParameter("OEEDateTo", oEEDateTo) :
                new ObjectParameter("OEEDateTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSHeaderByDistanceDate_Result>("get_OEEMSHeaderByDistanceDate", oEEDateFromParameter, oEEDateToParameter);
        }
    
        public virtual ObjectResult<get_OEEMSHeaderByID_Result> get_OEEMSHeaderByID(string oEEID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSHeaderByID_Result>("get_OEEMSHeaderByID", oEEIDParameter);
        }
    
        public virtual ObjectResult<get_OEEMSHeaderByStatus_Result> get_OEEMSHeaderByStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSHeaderByStatus_Result>("get_OEEMSHeaderByStatus");
        }
    
        public virtual ObjectResult<get_OEEMSWeekByDate_Result> get_OEEMSWeekByDate(string oEEDate, Nullable<int> chk)
        {
            var oEEDateParameter = oEEDate != null ?
                new ObjectParameter("OEEDate", oEEDate) :
                new ObjectParameter("OEEDate", typeof(string));
    
            var chkParameter = chk.HasValue ?
                new ObjectParameter("Chk", chk) :
                new ObjectParameter("Chk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSWeekByDate_Result>("get_OEEMSWeekByDate", oEEDateParameter, chkParameter);
        }
    
        public virtual ObjectResult<get_OEEMSWeekByDate_Hung_Result> get_OEEMSWeekByDate_Hung(string oEEDate, Nullable<int> chk)
        {
            var oEEDateParameter = oEEDate != null ?
                new ObjectParameter("OEEDate", oEEDate) :
                new ObjectParameter("OEEDate", typeof(string));
    
            var chkParameter = chk.HasValue ?
                new ObjectParameter("Chk", chk) :
                new ObjectParameter("Chk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSWeekByDate_Hung_Result>("get_OEEMSWeekByDate_Hung", oEEDateParameter, chkParameter);
        }
    
        public virtual ObjectResult<get_OEEMSWeekProcessByDate_Result> get_OEEMSWeekProcessByDate(string oEEDate, Nullable<int> chk)
        {
            var oEEDateParameter = oEEDate != null ?
                new ObjectParameter("OEEDate", oEEDate) :
                new ObjectParameter("OEEDate", typeof(string));
    
            var chkParameter = chk.HasValue ?
                new ObjectParameter("Chk", chk) :
                new ObjectParameter("Chk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSWeekProcessByDate_Result>("get_OEEMSWeekProcessByDate", oEEDateParameter, chkParameter);
        }
    
        public virtual int LOG_UPDATE(string v_F000, string v_F002, string v_F003, string v_F004)
        {
            var v_F000Parameter = v_F000 != null ?
                new ObjectParameter("V_F000", v_F000) :
                new ObjectParameter("V_F000", typeof(string));
    
            var v_F002Parameter = v_F002 != null ?
                new ObjectParameter("V_F002", v_F002) :
                new ObjectParameter("V_F002", typeof(string));
    
            var v_F003Parameter = v_F003 != null ?
                new ObjectParameter("V_F003", v_F003) :
                new ObjectParameter("V_F003", typeof(string));
    
            var v_F004Parameter = v_F004 != null ?
                new ObjectParameter("V_F004", v_F004) :
                new ObjectParameter("V_F004", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOG_UPDATE", v_F000Parameter, v_F002Parameter, v_F003Parameter, v_F004Parameter);
        }
    
        public virtual int sp_ActionLog(string actionName, string controllerName, string method, string content, string detail, string userName, Nullable<System.DateTime> date)
        {
            var actionNameParameter = actionName != null ?
                new ObjectParameter("ActionName", actionName) :
                new ObjectParameter("ActionName", typeof(string));
    
            var controllerNameParameter = controllerName != null ?
                new ObjectParameter("ControllerName", controllerName) :
                new ObjectParameter("ControllerName", typeof(string));
    
            var methodParameter = method != null ?
                new ObjectParameter("Method", method) :
                new ObjectParameter("Method", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            var detailParameter = detail != null ?
                new ObjectParameter("Detail", detail) :
                new ObjectParameter("Detail", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActionLog", actionNameParameter, controllerNameParameter, methodParameter, contentParameter, detailParameter, userNameParameter, dateParameter);
        }
    
        public virtual ObjectResult<string> sp_DelOEEMS_DownTime(Nullable<int> iD, string oEEID, string dTID, string workPieceID, string processID, string fromTime, string toTime, string note, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var dTIDParameter = dTID != null ?
                new ObjectParameter("DTID", dTID) :
                new ObjectParameter("DTID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var fromTimeParameter = fromTime != null ?
                new ObjectParameter("FromTime", fromTime) :
                new ObjectParameter("FromTime", typeof(string));
    
            var toTimeParameter = toTime != null ?
                new ObjectParameter("ToTime", toTime) :
                new ObjectParameter("ToTime", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_DelOEEMS_DownTime", iDParameter, oEEIDParameter, dTIDParameter, workPieceIDParameter, processIDParameter, fromTimeParameter, toTimeParameter, noteParameter, userIDParameter);
        }
    
        public virtual int sp_DelOEEMS_emp(Nullable<int> iD, string oEEID, string eMPID, string workPieceID, string processID, string note, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var eMPIDParameter = eMPID != null ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DelOEEMS_emp", iDParameter, oEEIDParameter, eMPIDParameter, workPieceIDParameter, processIDParameter, noteParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_DelOEEMS_Header(string oEEID, Nullable<System.DateTime> oEEDate, string projectID, string compID, string sizeID, string userID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var oEEDateParameter = oEEDate.HasValue ?
                new ObjectParameter("OEEDate", oEEDate) :
                new ObjectParameter("OEEDate", typeof(System.DateTime));
    
            var projectIDParameter = projectID != null ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(string));
    
            var compIDParameter = compID != null ?
                new ObjectParameter("CompID", compID) :
                new ObjectParameter("CompID", typeof(string));
    
            var sizeIDParameter = sizeID != null ?
                new ObjectParameter("SizeID", sizeID) :
                new ObjectParameter("SizeID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_DelOEEMS_Header", oEEIDParameter, oEEDateParameter, projectIDParameter, compIDParameter, sizeIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_DelOEEMS_Process(Nullable<int> iD, string oEEID, string processID, string workPieceID, Nullable<int> planTime, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var planTimeParameter = planTime.HasValue ?
                new ObjectParameter("PlanTime", planTime) :
                new ObjectParameter("PlanTime", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_DelOEEMS_Process", iDParameter, oEEIDParameter, processIDParameter, workPieceIDParameter, planTimeParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_DelOEEMS_RealTime(Nullable<int> iD, string oEEID, string eMPID, string workPieceID, string processID, string fromTime, string toTime, string note, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var eMPIDParameter = eMPID != null ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var fromTimeParameter = fromTime != null ?
                new ObjectParameter("FromTime", fromTime) :
                new ObjectParameter("FromTime", typeof(string));
    
            var toTimeParameter = toTime != null ?
                new ObjectParameter("ToTime", toTime) :
                new ObjectParameter("ToTime", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_DelOEEMS_RealTime", iDParameter, oEEIDParameter, eMPIDParameter, workPieceIDParameter, processIDParameter, fromTimeParameter, toTimeParameter, noteParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_DelProject(string projectID, string projectName, string categoryID, string customerID, string userID)
        {
            var projectIDParameter = projectID != null ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(string));
    
            var projectNameParameter = projectName != null ?
                new ObjectParameter("ProjectName", projectName) :
                new ObjectParameter("ProjectName", typeof(string));
    
            var categoryIDParameter = categoryID != null ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(string));
    
            var customerIDParameter = customerID != null ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_DelProject", projectIDParameter, projectNameParameter, categoryIDParameter, customerIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_EndOEEMS_Header(string oEEID, string userID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_EndOEEMS_Header", oEEIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_EndOEEMS_Header_auto(string oEEID, string userID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_EndOEEMS_Header_auto", oEEIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_EndOEEMS_Process(Nullable<int> iD, string oEEID, string processID, string workPieceID, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_EndOEEMS_Process", iDParameter, oEEIDParameter, processIDParameter, workPieceIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_EndOEEMS_Process_auto(string oEEID, string processID, string workPieceID, string userID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_EndOEEMS_Process_auto", oEEIDParameter, processIDParameter, workPieceIDParameter, userIDParameter);
        }
    
        public virtual int sp_InsLogUser(string userName, string tabletName, string seriNo, string iMEI, Nullable<bool> status)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var tabletNameParameter = tabletName != null ?
                new ObjectParameter("TabletName", tabletName) :
                new ObjectParameter("TabletName", typeof(string));
    
            var seriNoParameter = seriNo != null ?
                new ObjectParameter("SeriNo", seriNo) :
                new ObjectParameter("SeriNo", typeof(string));
    
            var iMEIParameter = iMEI != null ?
                new ObjectParameter("IMEI", iMEI) :
                new ObjectParameter("IMEI", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsLogUser", userNameParameter, tabletNameParameter, seriNoParameter, iMEIParameter, statusParameter);
        }
    
        public virtual ObjectResult<string> sp_InsOEEMS_DownTime(Nullable<int> iD, string oEEID, string dTID, string workPieceID, string processID, string fromTime, string toTime, string note, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var dTIDParameter = dTID != null ?
                new ObjectParameter("DTID", dTID) :
                new ObjectParameter("DTID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var fromTimeParameter = fromTime != null ?
                new ObjectParameter("FromTime", fromTime) :
                new ObjectParameter("FromTime", typeof(string));
    
            var toTimeParameter = toTime != null ?
                new ObjectParameter("ToTime", toTime) :
                new ObjectParameter("ToTime", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_InsOEEMS_DownTime", iDParameter, oEEIDParameter, dTIDParameter, workPieceIDParameter, processIDParameter, fromTimeParameter, toTimeParameter, noteParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_InsOEEMS_Emp(Nullable<int> iD, string oEEID, string eMPID, string workPieceID, string processID, string note, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var eMPIDParameter = eMPID != null ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_InsOEEMS_Emp", iDParameter, oEEIDParameter, eMPIDParameter, workPieceIDParameter, processIDParameter, noteParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_InsOEEMS_Header(string oEEID, Nullable<System.DateTime> oEEDate, string projectID, string compID, string sizeID, string userID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var oEEDateParameter = oEEDate.HasValue ?
                new ObjectParameter("OEEDate", oEEDate) :
                new ObjectParameter("OEEDate", typeof(System.DateTime));
    
            var projectIDParameter = projectID != null ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(string));
    
            var compIDParameter = compID != null ?
                new ObjectParameter("CompID", compID) :
                new ObjectParameter("CompID", typeof(string));
    
            var sizeIDParameter = sizeID != null ?
                new ObjectParameter("SizeID", sizeID) :
                new ObjectParameter("SizeID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_InsOEEMS_Header", oEEIDParameter, oEEDateParameter, projectIDParameter, compIDParameter, sizeIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_InsOEEMS_PercentComplete(Nullable<int> iD, string oEEID, Nullable<int> weedOfYear, Nullable<double> percentCom, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var weedOfYearParameter = weedOfYear.HasValue ?
                new ObjectParameter("WeedOfYear", weedOfYear) :
                new ObjectParameter("WeedOfYear", typeof(int));
    
            var percentComParameter = percentCom.HasValue ?
                new ObjectParameter("PercentCom", percentCom) :
                new ObjectParameter("PercentCom", typeof(double));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_InsOEEMS_PercentComplete", iDParameter, oEEIDParameter, weedOfYearParameter, percentComParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_InsOEEMS_Process(Nullable<int> iD, string oEEID, Nullable<int> processID, Nullable<int> workPieceID, Nullable<int> planTime, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var processIDParameter = processID.HasValue ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(int));
    
            var workPieceIDParameter = workPieceID.HasValue ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(int));
    
            var planTimeParameter = planTime.HasValue ?
                new ObjectParameter("PlanTime", planTime) :
                new ObjectParameter("PlanTime", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_InsOEEMS_Process", iDParameter, oEEIDParameter, processIDParameter, workPieceIDParameter, planTimeParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_InsOEEMS_RealTime(Nullable<int> iD, string oEEID, string eMPID, string workPieceID, string processID, string fromTime, string toTime, string note, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var eMPIDParameter = eMPID != null ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(string));
    
            var workPieceIDParameter = workPieceID != null ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var fromTimeParameter = fromTime != null ?
                new ObjectParameter("FromTime", fromTime) :
                new ObjectParameter("FromTime", typeof(string));
    
            var toTimeParameter = toTime != null ?
                new ObjectParameter("ToTime", toTime) :
                new ObjectParameter("ToTime", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_InsOEEMS_RealTime", iDParameter, oEEIDParameter, eMPIDParameter, workPieceIDParameter, processIDParameter, fromTimeParameter, toTimeParameter, noteParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> sp_InsProject(string projectID, string projectName, string categoryID, string customerID, string userID)
        {
            var projectIDParameter = projectID != null ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(string));
    
            var projectNameParameter = projectName != null ?
                new ObjectParameter("ProjectName", projectName) :
                new ObjectParameter("ProjectName", typeof(string));
    
            var categoryIDParameter = categoryID != null ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(string));
    
            var customerIDParameter = customerID != null ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_InsProject", projectIDParameter, projectNameParameter, categoryIDParameter, customerIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<sp_tblDepartmentProcess_Get_Result> sp_tblDepartmentProcess_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblDepartmentProcess_Get_Result>("sp_tblDepartmentProcess_Get");
        }
    
        public virtual ObjectResult<sp_tblDownTime_Get_Result> sp_tblDownTime_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblDownTime_Get_Result>("sp_tblDownTime_Get");
        }
    
        public virtual ObjectResult<sp_tblProject_Get_Result> sp_tblProject_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblProject_Get_Result>("sp_tblProject_Get");
        }
    
        public virtual ObjectResult<sp_tblProjectComp_Get_Result> sp_tblProjectComp_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblProjectComp_Get_Result>("sp_tblProjectComp_Get");
        }
    
        public virtual ObjectResult<sp_tblProjectSize_Get_Result> sp_tblProjectSize_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblProjectSize_Get_Result>("sp_tblProjectSize_Get");
        }
    
        public virtual ObjectResult<sp_tblWorkpiece_Get_Result> sp_tblWorkpiece_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblWorkpiece_Get_Result>("sp_tblWorkpiece_Get");
        }
    
        public virtual ObjectResult<sp_tblWorkpieceProcess_edit_Get_Result> sp_tblWorkpieceProcess_edit_Get(string oEEID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblWorkpieceProcess_edit_Get_Result>("sp_tblWorkpieceProcess_edit_Get", oEEIDParameter);
        }
    
        public virtual ObjectResult<sp_tblWorkpieceProcess_Get_Result> sp_tblWorkpieceProcess_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblWorkpieceProcess_Get_Result>("sp_tblWorkpieceProcess_Get");
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<get_OEEMSHeaderByDistanceDate_new_Result> get_OEEMSHeaderByDistanceDate_new(string oEEDateFrom, string oEEDateTo)
        {
            var oEEDateFromParameter = oEEDateFrom != null ?
                new ObjectParameter("OEEDateFrom", oEEDateFrom) :
                new ObjectParameter("OEEDateFrom", typeof(string));
    
            var oEEDateToParameter = oEEDateTo != null ?
                new ObjectParameter("OEEDateTo", oEEDateTo) :
                new ObjectParameter("OEEDateTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSHeaderByDistanceDate_new_Result>("get_OEEMSHeaderByDistanceDate_new", oEEDateFromParameter, oEEDateToParameter);
        }
    
        public virtual ObjectResult<string> sp_udpOEEMS_ChangeProcess(string oEEID, Nullable<int> workPieceID, Nullable<int> processIDOld, Nullable<int> processIDNew, string userID)
        {
            var oEEIDParameter = oEEID != null ?
                new ObjectParameter("OEEID", oEEID) :
                new ObjectParameter("OEEID", typeof(string));
    
            var workPieceIDParameter = workPieceID.HasValue ?
                new ObjectParameter("WorkPieceID", workPieceID) :
                new ObjectParameter("WorkPieceID", typeof(int));
    
            var processIDOldParameter = processIDOld.HasValue ?
                new ObjectParameter("ProcessIDOld", processIDOld) :
                new ObjectParameter("ProcessIDOld", typeof(int));
    
            var processIDNewParameter = processIDNew.HasValue ?
                new ObjectParameter("ProcessIDNew", processIDNew) :
                new ObjectParameter("ProcessIDNew", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_udpOEEMS_ChangeProcess", oEEIDParameter, workPieceIDParameter, processIDOldParameter, processIDNewParameter, userIDParameter);
        }
    
        public virtual ObjectResult<get_OEEMSWeekByDate_1_Result> get_OEEMSWeekByDate_1(string oEEDate, Nullable<int> chk)
        {
            var oEEDateParameter = oEEDate != null ?
                new ObjectParameter("OEEDate", oEEDate) :
                new ObjectParameter("OEEDate", typeof(string));
    
            var chkParameter = chk.HasValue ?
                new ObjectParameter("Chk", chk) :
                new ObjectParameter("Chk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSWeekByDate_1_Result>("get_OEEMSWeekByDate_1", oEEDateParameter, chkParameter);
        }
    
        public virtual ObjectResult<get_OEEMSWeekProcessByDate_1_Result> get_OEEMSWeekProcessByDate_1(string oEEDate, Nullable<int> chk)
        {
            var oEEDateParameter = oEEDate != null ?
                new ObjectParameter("OEEDate", oEEDate) :
                new ObjectParameter("OEEDate", typeof(string));
    
            var chkParameter = chk.HasValue ?
                new ObjectParameter("Chk", chk) :
                new ObjectParameter("Chk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSWeekProcessByDate_1_Result>("get_OEEMSWeekProcessByDate_1", oEEDateParameter, chkParameter);
        }
    
        public virtual ObjectResult<get_OEEMSWeekWorkpieceByDate_Result> get_OEEMSWeekWorkpieceByDate(string oEEDate, Nullable<int> chk)
        {
            var oEEDateParameter = oEEDate != null ?
                new ObjectParameter("OEEDate", oEEDate) :
                new ObjectParameter("OEEDate", typeof(string));
    
            var chkParameter = chk.HasValue ?
                new ObjectParameter("Chk", chk) :
                new ObjectParameter("Chk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSWeekWorkpieceByDate_Result>("get_OEEMSWeekWorkpieceByDate", oEEDateParameter, chkParameter);
        }
    
        public virtual ObjectResult<get_OEEMSWeekWorkpieceByDate_1_Result> get_OEEMSWeekWorkpieceByDate_1(string oEEDate, Nullable<int> chk)
        {
            var oEEDateParameter = oEEDate != null ?
                new ObjectParameter("OEEDate", oEEDate) :
                new ObjectParameter("OEEDate", typeof(string));
    
            var chkParameter = chk.HasValue ?
                new ObjectParameter("Chk", chk) :
                new ObjectParameter("Chk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OEEMSWeekWorkpieceByDate_1_Result>("get_OEEMSWeekWorkpieceByDate_1", oEEDateParameter, chkParameter);
        }
    }
}
