//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.OEEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDownTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDownTime()
        {
            this.tblOEEMS_DownTime = new HashSet<tblOEEMS_DownTime>();
        }
    
        public int DTID { get; set; }
        public int GroupID { get; set; }
        public string DTName { get; set; }
        public string Note { get; set; }
    
        public virtual tblProcess tblProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOEEMS_DownTime> tblOEEMS_DownTime { get; set; }
    }
}
