//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.OEEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public string F000 { get; set; }
        public System.DateTime F001 { get; set; }
        public string F002 { get; set; }
        public string F003 { get; set; }
        public string F004 { get; set; }
    }
}
