//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.OEEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOEEMS_Process
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOEEMS_Process()
        {
            this.tblOEEMS_DownTime = new HashSet<tblOEEMS_DownTime>();
            this.tblOEEMS_Employee = new HashSet<tblOEEMS_Employee>();
        }
    
        public long ID { get; set; }
        public string OEEID { get; set; }
        public int ProcessID { get; set; }
        public int WorkPieceID { get; set; }
        public int PlanTime { get; set; }
        public Nullable<int> RealTime { get; set; }
        public Nullable<int> DownTime { get; set; }
        public Nullable<double> OEE { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOEEMS_DownTime> tblOEEMS_DownTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOEEMS_Employee> tblOEEMS_Employee { get; set; }
        public virtual tblOEEMS_Header tblOEEMS_Header { get; set; }
        public virtual tblOEEMS_Status tblOEEMS_Status { get; set; }
        public virtual tblWorkpieceProcess tblWorkpieceProcess { get; set; }
    }
}
