//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.OEEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOEEMS_PercentComplete
    {
        public long ID { get; set; }
        public string OEEID { get; set; }
        public Nullable<System.DateTime> DateOfWeek { get; set; }
        public int WeedOfYear { get; set; }
        public Nullable<double> PercentCom { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual tblOEEMS_Header tblOEEMS_Header { get; set; }
    }
}
