//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.OEEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOEEMS_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOEEMS_Employee()
        {
            this.tblOEEMS_RealTime = new HashSet<tblOEEMS_RealTime>();
        }
    
        public long ID { get; set; }
        public string OEEID { get; set; }
        public string EMPID { get; set; }
        public int WorkPieceID { get; set; }
        public int ProcessID { get; set; }
        public string Note { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual tblOEEMS_Process tblOEEMS_Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOEEMS_RealTime> tblOEEMS_RealTime { get; set; }
    }
}
