//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.OEEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOEEMS_RealTime
    {
        public long ID { get; set; }
        public string OEEID { get; set; }
        public string EMPID { get; set; }
        public int WorkPieceID { get; set; }
        public int ProcessID { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public string Note { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsDownTime { get; set; }
    
        public virtual tblOEEMS_Employee tblOEEMS_Employee { get; set; }
    }
}
