//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.OEEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVersionTablet
    {
        public int ID { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    }
}
