//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.OEEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkpieceProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorkpieceProcess()
        {
            this.tblOEEMS_Process = new HashSet<tblOEEMS_Process>();
        }
    
        public int WorkpieceID { get; set; }
        public int ProcessID { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOEEMS_Process> tblOEEMS_Process { get; set; }
        public virtual tblProcess tblProcess { get; set; }
        public virtual tblWorkpiece tblWorkpiece { get; set; }
    }
}
