//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.VNT86
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKIN_WS_NEW
    {
        public int MESOKEY { get; set; }
        public string C400 { get; set; }
        public Nullable<double> C401 { get; set; }
        public Nullable<double> C402 { get; set; }
        public Nullable<double> C403 { get; set; }
        public Nullable<System.DateTime> C404 { get; set; }
        public string C405 { get; set; }
        public string C406 { get; set; }
        public int C409 { get; set; }
        public string C412 { get; set; }
        public string C417 { get; set; }
    }
}
