//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.VNT86
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VNT86Entities : DbContext
    {
        public VNT86Entities()
            : base("name=VNT86Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STOCKIN_WS_NEW> STOCKIN_WS_NEW { get; set; }
    
        public virtual ObjectResult<sp_FinanceDAByProduct_Result> sp_FinanceDAByProduct(string productCode)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FinanceDAByProduct_Result>("sp_FinanceDAByProduct", productCodeParameter);
        }
    
        public virtual ObjectResult<sp_FinanceDAGet_Result> sp_FinanceDAGet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FinanceDAGet_Result>("sp_FinanceDAGet");
        }
    }
}
