//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.FingerScan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LogFinger_Login_M2
    {
        public long ID { get; set; }
        public Nullable<int> MachineNumber { get; set; }
        public Nullable<int> IndRegID { get; set; }
        public Nullable<int> VerifyMode { get; set; }
        public Nullable<int> InOutMode { get; set; }
        public Nullable<System.DateTime> DateTimeRecord { get; set; }
    }
}
