//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.SCP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SCPEntities : DbContext
    {
        public SCPEntities()
            : base("name=SCPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<show_data_Result> show_data(string v_Year, string v_month, string v_venderName)
        {
            var v_YearParameter = v_Year != null ?
                new ObjectParameter("V_Year", v_Year) :
                new ObjectParameter("V_Year", typeof(string));
    
            var v_monthParameter = v_month != null ?
                new ObjectParameter("V_month", v_month) :
                new ObjectParameter("V_month", typeof(string));
    
            var v_venderNameParameter = v_venderName != null ?
                new ObjectParameter("V_venderName", v_venderName) :
                new ObjectParameter("V_venderName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<show_data_Result>("show_data", v_YearParameter, v_monthParameter, v_venderNameParameter);
        }
    
        public virtual ObjectResult<show_data_category_Result> show_data_category(string v_Year, string v_month)
        {
            var v_YearParameter = v_Year != null ?
                new ObjectParameter("V_Year", v_Year) :
                new ObjectParameter("V_Year", typeof(string));
    
            var v_monthParameter = v_month != null ?
                new ObjectParameter("V_month", v_month) :
                new ObjectParameter("V_month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<show_data_category_Result>("show_data_category", v_YearParameter, v_monthParameter);
        }
    }
}
