//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.Meal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback_Reply
    {
        public int ID { get; set; }
        public Nullable<int> ConversationsID { get; set; }
        public string UserName { get; set; }
        public string TextContain { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserAdd { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
    
        public virtual Feedback Feedback { get; set; }
    }
}
