//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.Meal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealDelivery
    {
        public long ID { get; set; }
        public int UserName { get; set; }
        public System.DateTime DateAdd { get; set; }
        public Nullable<int> MachineNumberID { get; set; }
        public Nullable<int> ShiftWorkID { get; set; }
        public Nullable<int> MenuMealID { get; set; }
    
        public virtual MenuMeal MenuMeal { get; set; }
        public virtual ShiftWork ShiftWork { get; set; }
    }
}
