//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.Meal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MealControlEntities : DbContext
    {
        public MealControlEntities()
            : base("name=MealControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Feedback_Reply> Feedback_Reply { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialType> MaterialTypes { get; set; }
        public virtual DbSet<MealDelivery> MealDeliveries { get; set; }
        public virtual DbSet<MealOrderException> MealOrderExceptions { get; set; }
        public virtual DbSet<MealSchedule> MealSchedules { get; set; }
        public virtual DbSet<MenuMeal> MenuMeals { get; set; }
        public virtual DbSet<MenuMealDetail> MenuMealDetails { get; set; }
        public virtual DbSet<OrderMeal> OrderMeals { get; set; }
        public virtual DbSet<ShiftWork> ShiftWorks { get; set; }
        public virtual DbSet<TimeLimitOrder> TimeLimitOrders { get; set; }
    
        public virtual ObjectResult<sp_DeliveryInstantNoodles_Get_Result> sp_DeliveryInstantNoodles_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DeliveryInstantNoodles_Get_Result>("sp_DeliveryInstantNoodles_Get");
        }
    
        public virtual ObjectResult<sp_MealOrderException_Get_Result> sp_MealOrderException_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MealOrderException_Get_Result>("sp_MealOrderException_Get");
        }
    
        public virtual ObjectResult<sp_MealSchedule_Child_Result> sp_MealSchedule_Child(Nullable<int> shiftWork, Nullable<System.DateTime> date)
        {
            var shiftWorkParameter = shiftWork.HasValue ?
                new ObjectParameter("ShiftWork", shiftWork) :
                new ObjectParameter("ShiftWork", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MealSchedule_Child_Result>("sp_MealSchedule_Child", shiftWorkParameter, dateParameter);
        }
    
        public virtual ObjectResult<sp_MealSchedule_GetByDay_Result> sp_MealSchedule_GetByDay(string from, string to)
        {
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MealSchedule_GetByDay_Result>("sp_MealSchedule_GetByDay", fromParameter, toParameter);
        }
    
        public virtual ObjectResult<sp_MealSchedule_Parent_Result> sp_MealSchedule_Parent(Nullable<int> shiftWork, Nullable<System.DateTime> date)
        {
            var shiftWorkParameter = shiftWork.HasValue ?
                new ObjectParameter("ShiftWork", shiftWork) :
                new ObjectParameter("ShiftWork", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MealSchedule_Parent_Result>("sp_MealSchedule_Parent", shiftWorkParameter, dateParameter);
        }
    
        public virtual ObjectResult<sp_OrderMeal_GetDay_Result> sp_OrderMeal_GetDay(string day, string user)
        {
            var dayParameter = day != null ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OrderMeal_GetDay_Result>("sp_OrderMeal_GetDay", dayParameter, userParameter);
        }
    
        public virtual ObjectResult<sp_MealOrderException_Search_Result> sp_MealOrderException_Search(string date)
        {
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MealOrderException_Search_Result>("sp_MealOrderException_Search", dateParameter);
        }
    
        public virtual ObjectResult<sp_DeliveryInstantNoodles_Search_Result> sp_DeliveryInstantNoodles_Search(string date)
        {
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DeliveryInstantNoodles_Search_Result>("sp_DeliveryInstantNoodles_Search", dateParameter);
        }
    
        public virtual ObjectResult<sp_ShiftWorkGet_Result> sp_ShiftWorkGet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ShiftWorkGet_Result>("sp_ShiftWorkGet");
        }
    
        public virtual ObjectResult<sp_OrderMealOffline_Get_Result> sp_OrderMealOffline_Get(string day)
        {
            var dayParameter = day != null ?
                new ObjectParameter("Day", day) :
                new ObjectParameter("Day", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OrderMealOffline_Get_Result>("sp_OrderMealOffline_Get", dayParameter);
        }
    
        public virtual int sp_ActionLog(string actionName, string controllerName, string method, string content, string detail, string userName, Nullable<System.DateTime> date)
        {
            var actionNameParameter = actionName != null ?
                new ObjectParameter("ActionName", actionName) :
                new ObjectParameter("ActionName", typeof(string));
    
            var controllerNameParameter = controllerName != null ?
                new ObjectParameter("ControllerName", controllerName) :
                new ObjectParameter("ControllerName", typeof(string));
    
            var methodParameter = method != null ?
                new ObjectParameter("Method", method) :
                new ObjectParameter("Method", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            var detailParameter = detail != null ?
                new ObjectParameter("Detail", detail) :
                new ObjectParameter("Detail", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActionLog", actionNameParameter, controllerNameParameter, methodParameter, contentParameter, detailParameter, userNameParameter, dateParameter);
        }
    }
}
