//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.UserManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRoleButton
    {
        public string RoleID { get; set; }
        public string ButtonID { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetButton AspNetButton { get; set; }
        public virtual AspNetRolesDev AspNetRolesDev { get; set; }
    }
}
