//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.UserManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserModuleRole
    {
        public string UserID { get; set; }
        public int ModuleID { get; set; }
        public string RoleID { get; set; }
        public string Description { get; set; }
    }
}
