//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.UserManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserRolesForApp
    {
        public string UserId { get; set; }
        public string RoleId { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetRolesForApp AspNetRolesForApp { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
