//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.UserManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysLogfileAction
    {
        public long ID { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public string Method { get; set; }
        public string Content { get; set; }
        public string Detail { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
    }
}
