//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.Menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventList
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> EventDay { get; set; }
        public string Title1_EG { get; set; }
        public string Title1_GR { get; set; }
        public string Title1_VN { get; set; }
        public string Title2_EG { get; set; }
        public string Title2_GR { get; set; }
        public string Title2_VN { get; set; }
        public string Title3_EG { get; set; }
        public string Title3_GR { get; set; }
        public string Title3_VN { get; set; }
        public string TableName { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserAdd { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string UserUpd { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
    }
}
