//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.Menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSComputer
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> DateMark { get; set; }
        public Nullable<double> TotalScore { get; set; }
        public Nullable<double> TotalPercent { get; set; }
        public Nullable<int> Mark1 { get; set; }
        public string Factor1 { get; set; }
        public string Note1 { get; set; }
        public Nullable<int> Mark2 { get; set; }
        public string Factor2 { get; set; }
        public string Note2 { get; set; }
        public Nullable<int> Mark3 { get; set; }
        public string Factor3 { get; set; }
        public string Note3 { get; set; }
        public Nullable<int> Mark4 { get; set; }
        public string Factor4 { get; set; }
        public string Note4 { get; set; }
        public Nullable<int> Mark5 { get; set; }
        public string Factor5 { get; set; }
        public string Note5 { get; set; }
        public Nullable<int> Mark6 { get; set; }
        public string Factor6 { get; set; }
        public string Note6 { get; set; }
        public Nullable<int> Mark7 { get; set; }
        public string Factor7 { get; set; }
        public string Note7 { get; set; }
        public Nullable<int> Mark8 { get; set; }
        public string Factor8 { get; set; }
        public string Note8 { get; set; }
        public Nullable<int> Mark9 { get; set; }
        public string Factor9 { get; set; }
        public string Note9 { get; set; }
        public Nullable<int> Mark10 { get; set; }
        public string Factor10 { get; set; }
        public string Note10 { get; set; }
        public Nullable<int> Mark11 { get; set; }
        public string Factor11 { get; set; }
        public string Note11 { get; set; }
        public Nullable<int> Mark12 { get; set; }
        public string Factor12 { get; set; }
        public string Note12 { get; set; }
        public Nullable<int> Mark13 { get; set; }
        public string Factor13 { get; set; }
        public string Note13 { get; set; }
        public Nullable<int> Mark14 { get; set; }
        public string Factor14 { get; set; }
        public string Note14 { get; set; }
        public Nullable<int> Mark15 { get; set; }
        public string Factor15 { get; set; }
        public string Note15 { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string UserAdd { get; set; }
        public string UserUpd { get; set; }
        public Nullable<System.DateTime> DateUpd { get; set; }
        public Nullable<double> TotalMark { get; set; }
    }
}
