//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.Menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListWorkLoad
    {
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<double> WorkingHour { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateWork { get; set; }
        public Nullable<double> TotalWorking { get; set; }
        public Nullable<double> Percen { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string UserAdd { get; set; }
        public Nullable<bool> Active { get; set; }
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
    }
}
