//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.Menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaturdayOffPlanning
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Content { get; set; }
        public string DepartmentID { get; set; }
        public string TableName { get; set; }
        public System.DateTime DateOff { get; set; }
        public string PCIDAdd { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
    }
}
