//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramasVietNam.Models.Menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Translation
    {
        public int LanguageID { get; set; }
        public string LanguageCode { get; set; }
        public int NameID { get; set; }
        public string TableName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string PCIDAdd { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
    
        public virtual sys_Language sys_Language { get; set; }
    }
}
